# Generated by Django 5.0.6 on 2024-07-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupapprovalqueue',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
